### ISSUE TITLE
GlyphLayout has problems measuring CFF gylphs

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#107]
```cs
    public static float Measure(string text) => new Typography.TextLayout.GlyphLayout() {
      Typeface = new Typography.OpenFont.OpenFontReader().Read(new System.IO.FileStream(Paths.LatinModernMath, System.IO.FileMode.Open))
    }.LayoutAndMeasureString(text.ToCharArray(), 0, text.Length, 20, out _).width;
```
Measure("1+1+1+1+1+1+1+1") returns 6.717154
I think some improper handling of CFF glyphs are happening here...

**Comment by prepare** [comment]
Thank you

fixed in https://github.com/LayoutFarm/Typography/commit/ff91aaa4a9b5156bb5277d12b612c85d6c07f664

also add measure string step-by-step code..
see https://github.com/LayoutFarm/Typography/commit/e26ed79efeba02fb1b6f87640bb3e27de24ac4bc

---
![measure_str](https://user-images.githubusercontent.com/7447159/40060100-fe6ff2be-587f-11e8-8389-276379d25247.png)

_pic 1: Measure string with current font setting, Press that button (1)_
