### ISSUE TITLE
LayoutAndMeasureString and Glyph.Bounds are not equal

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#118]
See sample => https://github.com/Happypig375/TypographyGlyphBoundsTest
![image](https://user-images.githubusercontent.com/19922066/40574525-6a51af84-6106-11e8-97b5-19834070ebf3.png)

**Comment by Happypig375** [comment]
This should be the cause of wrong glyphs being used in here.
![image](https://user-images.githubusercontent.com/19922066/40574598-53277f2c-6107-11e8-8729-c5da90042d3d.png)

**Comment by prepare** [comment]
Thank you for your report.

This  bug is fixed in => https://github.com/LayoutFarm/Typography/commit/c8c8a7bf43a415121a934b2ca41afec6dc6d9924

---
After correct ... + add show-glyph-bounds code => https://github.com/LayoutFarm/Typography/commit/5c9c4633103dd99c41a45d96044ce636a6adcf60

![glyph_bounds](https://user-images.githubusercontent.com/7447159/40576663-64b5b7e6-6124-11e8-8f66-576aefdd8ed2.png)

_pic 1:  latin-modern-math, gdi+ => MeasureTextSpan button shows each GlyphBounds_

**Comment by prepare** [comment]
umm ,,, let me fix it a little bit

**Comment by prepare** [comment]
Another example, GlyphBounds on Tahoma

![glyph_bounds3](https://user-images.githubusercontent.com/7447159/40576904-cbca2b26-6127-11e8-918c-c49e583b34be.png)

_pic 2: TTF font, tahoma, shows each GlyphBounds_
