### ISSUE TITLE
Caching unscaled path

### ISSUE THREAD

**Issue by acaly** [LayoutFarm/Typography#211]
Hi!

I am writing an application to draw text with Direct3D and Typography.One. The problem I encountered is, because the ```GlyphOutlineBuilder.BuildFromGlyph``` needs a font size parameter when generating the path to render (received with an ```IGlyphTranslator``` later), when all text is scaled, all cached paths need to be recalculated, which seems to be an expensive operation in real-time scenarios (it actually happens quite often, e.g., when user drags the window into a monitor with different DPI). As an optimization, probably it's better to cache the unscaled path (or triangulated triangle list) instead, which can be reused to generate the new cache when the font size changes (ideally with only one draw call for each character).

Currently the ```BuildFromGlyph``` method needs the font size parameter to scale the points internally. I am not familiar with how that scaling should be done. I would like to know whether it is safe to provide a fixed value here (e.g. 1) to calculate the path, and when rendering, manually scale all points in the path. Will this method lead to noticeable error in any case?

Thank you!

**Comment by prepare** [comment]
Why _BuildFromGlyph(Glyph glyph, float sizeInPoints)_,  or
_BuildFromGlyphIndex(ushort glyphIndex, float sizeInPoints)_ need size parameter?
---

![tahoma10pt](https://user-images.githubusercontent.com/7447159/85379153-a69f3f00-b565-11ea-9346-0e84f0fed3f0.png)

_Tahoma, 10pt with different hints, (A) no hint, (B) hint with truetype instructions, (C) Maxim's Agg hint with truetype instruction vertical only_

Because some 'Outline Font (.ttf, .otf) '  have **'Hint instructions'**
that will adjust the shape of font to 'fit the grid' or make it look better (sharper)
when the font size is small. 

At different small font size, the outline of font is adjust differently.

But when it go larger size=> usually not need that hint.

---

In my practice, I cache font outline at different small size for drawing a text that need sharp
look at small size.

but for a large size or quick draw, zoom in, zoom out, animation=> switch to use
a unscaled version => and scale it freely to specific size with transformation matrix :)

(a developer can cache it in proper form, The Typography.One does not have a cache system for that)

---

How to get unscaled outline version?
---
![build_from_glyph](https://user-images.githubusercontent.com/7447159/85380027-a2275600-b566-11ea-8336-1b9cabdbacff.png)

set sizeInPoints to value <0 (eg. -1) => you will get unscaled and unhinted outline version of the glyph.




----

How to scale the original glyph outline to specific size (point or pixel) ?
---

![build_from_glyph](https://user-images.githubusercontent.com/7447159/85380761-7fe20800-b567-11ea-86b0-516733358ee9.png)
_from Typography.OpenFont's Typeface.cs_

from the picture above, 
1. each font file has UnitPerEm value that may be different in each font,we need that value first
2. pointsPerInch AND resolution value may be different on other system. (the code use assumption    values)

so

If you have a box with height in **pixel unit**, and you want to scale the glyph to that height.
then use **CalculateScaleToPixel(float targetPixelSize)** to get the scale value.

But if you have to draw a font the specific in **point unit**.
Then you need to scale it with the value from **CalculateScaleToPixelFromPointSize(float targetPointSize)**

**Comment by acaly** [comment]
This is really helpful. Thank you!
