### ISSUE TITLE
MSDF Glyph Generation doesn't match Chlumsky's MSDFGen output

### ISSUE THREAD

**Issue by hexland** [LayoutFarm/Typography#43]
How up to date is your C# implementation to Chlumsky's MSDFGen tool (on which it is based)?
Glyph generation from your implementation does not match, and results in very blocky curves.

I modified the edgeColoringSimple function to match the MSDFGen implementation.
I also modified the ConvertToIntBmp in MsdfGen.cs to write out the color channels in the correct order (argb) (Although BMP stores the bytes in ABGR order, Intel ordering when the uint32_t is written out, changes that order - so we write out a uint32_t of argb, so that when BMP reads it in byte-by-byte, it comes in a ABGR)

I also wrote a little function that converts a contour list to a MSDFGen shape definition, to test the possibility that your contour list was somehow causing the problem.  So I use Typography.OpenFont to generate the shape definition, and then cut/paste the output into the commandline of MSDFGen.
Unfortunately, MSDFGen works just fine with that shape, so that confirms that the problem is with your C# implementation of MSDFGen.

I've compared the .cpp and .cs files, but I can't see where the divergence might be (admittedly, it was very very late at night)

(I've attached the DumpContours.cs for anyone that might find it useful)

I've also attached a couple of screenshots of the resultant MSDF glyph generated from both MSDFGen and Typeography.MSDFGen when run through the MSDF pixel shader.

[contours.txt](https://github.com/LayoutFarm/Typography/files/962777/contours.txt)

![msdfgen msdf screenshot](https://cloud.githubusercontent.com/assets/8294570/25502225/a6e753f6-2b4a-11e7-8910-e3be392cec62.png)
![msdfgen output](https://cloud.githubusercontent.com/assets/8294570/25502224/a6e207ac-2b4a-11e7-8dcd-a7df86f9d304.png)
![typeography msdf screenshot](https://cloud.githubusercontent.com/assets/8294570/25502223/a6e17fa8-2b4a-11e7-9827-388e43afb8c3.png)
![typeography output](https://cloud.githubusercontent.com/assets/8294570/25502226/a6e8b5ac-2b4a-11e7-9f81-cb43f633bd52.png)

**Comment by prepare** [comment]
I will fix it soon.

**Comment by hexland** [comment]
Thanks!  Let me know if you need any help/info/testing.

**Comment by prepare** [comment]
@hexland , the bug is fixing. 
Give me a time to upload the fix.

---
This is the early preview.

![msdf_test_02](https://cloud.githubusercontent.com/assets/7447159/25564411/012e7fd0-2ddd-11e7-9d36-61458e9d0c6a.png)

_pic 1: msdf [1] vs sdf[2]_, both texture are generated with the Typography.Msdf


![msdf_test_03](https://cloud.githubusercontent.com/assets/7447159/25564423/3686e0dc-2ddd-11e7-97f5-c34ba2d21762.png)
_pic 2: msdf, tahoma, '8' glyph_

**Comment by prepare** [comment]
@hexland ,

This bug was fixed in 8421df3a41ab6daad6ce3726c13ed0d010c176ba,
it came from I scale the glyph too small (than original) => so it lose of glyph resolution of distance field.

so I load the glyph without scaling it(set sizeInPoint=-1), and scale it later 1/64f of original size( the same as  Chlumsky 's code).


the  6efb94e6d71cb9e5fc6117a0d3ea70b36aa6dde2 is a minor refactor.

---

Thank you for your report

:)
