### ISSUE TITLE
Hello, Friends. I have a busy job for 2-3 weeks.

### ISSUE THREAD

**Issue by prepare** [LayoutFarm/Typography#47]
I visit here every day.
I will answer your questions.

But  I can't commit about 2-3 weeks.

:)

**Comment by BreyerW** [comment]
Hi, when looking for text rendering that is portable and graphic api-agnostic, i stumbled upon SharpFont first but thats a bit too low lvl and require c libs. I could live with that but then i found typography and im wondering if your solution support rendering to bitmaps like freetype's `LoadGlyph` followed by `Render` then getting byte array which represent requested bitmap. Unfortunetly, vbo and sdf solutions are still a bit too expensive for general purpose so thats why im asking about good old bitmap way. And if yes can i query metrics for that bitmap like in freetype's `Glyph.Metric`? (although i guess as long as you provide text layout engine i probably dont have to bother with that).

Other than that i wanted to say project look promising, although, subjectively, i think public api surface  is a bit messy (compared to sharpfont/freetype). Maybe demos are guilty here, all of them try to show more than necessary. It wouldnt be bad if there was one extra demo that is absolutely minimal (no gui frameworks, just graphic api like gl or dx and rendering predefined, hardcoded strings so that there is no need for textboxes/checkboxes etc.)

**Comment by prepare** [comment]
@BreyerW,  Thank you for your interest.


I admit that the code are too messy.
It should be re-arranged /cleaned up/ refactored. :)



The Typography lib reads all font data in a font file.
(including basic glyph data, glyph metrics,
and advanced layout data (OpenType/OpenFont)).
 
**I provide some samples that show 
how draw glyph from that data**

please see the WindowForm's GDI+ sample.
(see 
1. https://github.com/LayoutFarm/Typography/tree/master/Demo/Windows/PixelFarmSample.WinForms and 
2. https://github.com/LayoutFarm/Typography/blob/master/Demo/Windows/PixelFarmSample.WinForms/PixelFarm/GlyphTranslatorToVxs.cs)

It is very easy to draw a glyph on gdi+ surface.

---
![typo_1](https://cloud.githubusercontent.com/assets/7447159/23438561/f4bf870c-fe44-11e6-9882-a92796902822.png)
_pic 1:  Typography project's Solution Explorer View_

see pic1, I provide the example that use Typography and WinGdiPlus (1)


But if you don't want to use GDI+.
There is another advance Software Renderering Lib
called 'PixelFarm' (2) . This lib is platform-independent.

It renders directly to 'your' byte[] buffer.  
But this lib is under development :)

---

As soon as I finish the private project.
I will be back here again

**Comment by BreyerW** [comment]
Im aware of these samples, especially gdi one (rest i didnt examined closer) and my opinion on surface API come from this examination. The thing is, GDI is considered legacy (including GDI+) and thus will no longer be maintanained for other reasons than back-compat. In my project i abandoned GDI completely 
and im in the process of removing leftovers. Additionally i dont want to get dependency on yet another lib, that i might use only tiny fraction of potential. Finally, this functionality belong to typography than external lib.

Well it seems im gonna stick with SharpFont for now with minimal support for that lib and when typography become more mature im gonna jump in.

Thanks for answer.
